use_frameworks!

platform :ios, '10.0'

target 'ComponentKit_Example' do
  pod 'ComponentKit', :path => '../'

  target 'ComponentKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
